//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public long id { get; set; }
        public Nullable<long> Restaurant_id { get; set; }
        public string title { get; set; }
        public string image_name { get; set; }
        public string image_path { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
