//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_hour
    {
        public long id { get; set; }
        public string Day { get; set; }
        public System.TimeSpan From_time { get; set; }
        public Nullable<System.TimeSpan> To_time { get; set; }
        public Nullable<bool> Open_time { get; set; }
    }
}
